config/routes.rb
Rails.application.routes.draw do

	root 'welcome#index'
  

	devise_for :users, controllers: { registrations: 'user/registrations' }
	
	devise_scope :user do
		get 'users/edit', :to => 'user/registrations#edit'
    	get 'users/upgrade', :to => 'user/registrations#upgrade'
    	post 'users/downgrade', :to => 'user/registrations#downgrade'
	end
	
	authenticate :user do
		resources :charges
	end
	
	resources :wikis
	resources :collaborators, only: [:create, :destroy]
	resources :charges, only: [:new, :create]
	post '/stripe', :to => 'webhooks#receive'
	
	  
	
	
	
	
	
	
	
	
	
	
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators
  
	
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
	
	#before_action :authenticate_user!, :except => [:index, :show]
	rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
	
	def index
		@wikis = policy_scope(Wiki)
	end
	
	def show

		@wiki = Wiki.find(params[:id])
	end
	
	def new
		@wiki = Wiki.new
		authorize @wiki
	end
	
	def create
		@wiki = Wiki.new(wiki_params)
		authorize @wiki
		
		@wiki.user_id ||= current_user.id
		@wiki.private ||= false
		
		if @wiki.save
			flash[:notice] = "You have successfully created a new wiki!"
			redirect_to @wiki
		else 
			flash[:alert] = "Oops, something went wrong. Please Try Again!"
			render :new
		end
	end
	
	def edit
		@wiki = Wiki.find(params[:id])
		@collaborators = User.where(id: @wiki.collaborators.pluck(:user_id))
		authorize @wiki
	end
	
	def update
		@wiki = Wiki.find(params[:id])
		authorize @wiki
		
		@wiki.assign_attributes(wiki_params)
		
		if @wiki.save
			flash[:notice] = "You have edited your wiki!"
			redirect_to @wiki
		else 
			flash.now[:alert] = "Oops, something went wrong. Please Try Again!"
			return
		end
	end
	
	def destroy
		@wiki = Wiki.find(params[:id])
		authorize @wiki
		
		if @wiki.delete
			flash[:notice] = "Wiki successfully deleted!"
			redirect_to wikis_url
		else
			flash.now[:alert] =  "Wiki could not be deleted, please try again"
			return redirect_to wikis_url
		end
	end
		
	private
	
	def wiki_params
		params.require(:wiki).permit(:title, :body, :private)
	end
	
	def user_not_authorized(exception)
		policy_name = exception.policy.class.to_s.underscore
		
		flash[:alert] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
		case exception.query
		when "destroy?"
			redirect_to(edit_wiki_path)
		else
			redirect_to(new_user_session_path)
		end
	end
	
end

app/helpers/wikis_helper.rb
module WikisHelper
	
	require 'redcarpet'
	require 'redcarpet/render_strip'
	
	def markdown(text)
	    options = {
	      filter_html:     true,
	      #hard_wrap:       true,
	      #link_attributes: { rel: 'nofollow', target: "_blank" },
	      #space_after_headers: true,
	      #fenced_code_blocks: true
	    }
	
	    extensions = {
	      #autolink:           true,
	      #superscript:        true,
	      #disable_indented_code_blocks: true
	    }
	
	    renderer = Redcarpet::Render::HTML.new(options)
	    markdown = Redcarpet::Markdown.new(renderer, extensions)
	
	    markdown.render(text).html_safe
	end
	
	def markdown_strip(text)
		
		markdown = Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
		
		markdown.render(text)
	end
	
end

app/views/wikis/edit.html.erb
<h1>Edit Wiki: <%= @wiki.title %></h1>

<div id="title-divider"></div>

<div class="row">
	
	<div class="col-md-6">
		<%= form_for @wiki, action: :update do |f| %>
			<div class="form-group">
				<%= f.label 'Wiki Title' %>
				<%= f.text_field :title, class: "form-control" %> 
			</div>
			<div class="form-group">
				<%= f.label 'Wiki Body' %>
				<%= f.text_area :body, class: "form-control", rows: 15 %> 
			</div>
			
			<% if current_user.admin? || current_user.premium? %>
				<div class="form-group">
					<%= f.check_box(:private) %>
					<%= label_tag(:private, "Private Wiki?") %>
				</div>
			<% end %>
			
			<div class="form-group">
				<%= f.submit "Finish Editing", class: "btn btn-primary" %>
			</div>
			
		<% end %>
		
		<% if policy(@wiki).delete? %>
			<%= button_to "Delete This Wiki", @wiki, method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete \"#{@wiki.title}\"?" } %>
		<% end %>
		
		
		<br><br>
		<% if @wiki.private && ((current_user.premium? && @wiki.user_id == current_user.id) || current_user.admin?) %>
			<h3>Add Collaborators to this Wiki:</h3>
			<p>Enter an email to add a collaborator to the wiki so they can work on it when it is private.</p>
			
			<%= form_tag '/collaborators', method: :post do %>
				<%= text_field_tag 'email', nil, placeholder: "Enter the email of the user you want to add as a collaborator" %>
				<%= hidden_field_tag :id, @wiki.id %>
				<%= button_tag "Add Collaborator" %>
			<% end %> 
			
		
			<h3>Collaborators on this wiki:</h3>
			<ul>
			<% @collaborators.each do |user_id| %>
				<li>
					<%= "#{User.find(user_id).email}" %> 
					<% if current_user.admin? || @wiki.user_id == current_user.id %>
						<%= button_to "Remove Collaborator", collaborator_path(id: Collaborator.where(wiki_id:@wiki.id, user_id:user_id).first), method: :delete, class: "btn btn-warning" %>
					<% end %>
				</li>
			<% end %>
			</ul>
		
		<% end %>
	</div>
	
	<div class="col-md-6">
		<h3>Use Markdown to edit your Wiki Page: </h3>
		<p><strong>Headers:</strong></p>
		<p>Add a pound sign before text to create header text. More pound signs make the text smaller.</p>
		<p># Big Header 1</p>
		<p>## Header 2</p>
		<p>### Header 3, etc. </p>
		<p><strong>Bold and Italics:</strong></p>
		<p>Add asterisks or underscores around words phrases to bold and italicize them</p>
		<p>**Bold**</p>
		<p>*Italics*</p>
		<p><strong>Lists:</strong></p>
		<p>Add a dash before text to create bullet points, and a number before your text to create an ordered list.</p>
		<p>- Unordered List</p>
		<p>&nbsp;&nbsp;- Nested list (added space before the dash)</p>
		<p>1. Ordered list</p>
		<p>2. Ordered list</p>
		<p>&nbsp;&nbsp;1. Nested Ordered list</p>
	</div>
	
</div>

app/views/wikis/index.html.erb
<h1>List of All Wikis</h1>
<div id="title-divider"></div>
<div>
	<div class="row">
		
		<div class="col-md-10">
			
			<% @wikis.each do |wiki| %>
				<div class="wiki-container">
					<h3><%= link_to wiki.title, wiki_path(wiki.id), method: :get %></h3>
					<p class="wiki-body"><%= truncate(markdown_strip(wiki.body), length: 200) %></p>
				</div>
			<% end %>
	
		</div>
		<div class="col-md-2">
			<%= button_to "New Wiki", new_wiki_path, class: "btn btn-lg btn-primary", method: :get %>
		</div>
	
	</div>

app/views/wikis/new.html.erb
<h1>Create a New Wiki Page</h1>
<div id="title-divider"></div>
<div class="row">
	<div class="col-md-6">
		
		<%= form_for @wiki do |f| %>
			<div class="form-group">
				<%= f.label 'Wiki Title' %>
				<%= f.text_field :title, class: "form-control" %> 
			</div>
			<div class="form-group">
				<%= f.label 'Wiki Body' %>
				<%= f.text_area :body, class: "form-control", rows: 15 %> 
			</div>
			
			<% if current_user.admin? || current_user.premium? %>
				<div class="form-group">
					<%= f.check_box(:private) %>
					<%= label_tag(:private, "Private Wiki?") %>
				</div>
			<% end %>
			
			<div class="form-group">
				<%= f.submit "Submit", class: "btn btn-primary" %>
			</div>
			
		<% end %>

	</div>
	<div class="col-md-6">
		<h3>Use Markdown to create your Wiki Page: </h3>
		<p><strong>Headers:</strong></p>
		<p>Add a pound sign before text to create header text. More pound signs make the text smaller.</p>
		<p># Big Header 1</p>
		<p>## Header 2</p>
		<p>### Header 3, etc. </p>
		<p><strong>Bold and Italics:</strong></p>
		<p>Add asterisks or underscores around words phrases to bold and italicize them</p>
		<p>**Bold**</p>
		<p>*Italics*</p>
		<p><strong>Lists:</strong></p>
		<p>Add a dash before text to create bullet points, and a number before your text to create an ordered list.</p>
		<p>- Unordered List</p>
		<p>&nbsp;&nbsp;- Nested list (added space before the dash)</p>
		<p>1. Ordered list</p>
		<p>2. Ordered list</p>
		<p>&nbsp;&nbsp;1. Nested Ordered list</p>
	</div>
</div>

app/views/wikis/show.html.erb
<h1 id="wiki-title"><%= @wiki.title %> <%= "(private)" if @wiki.private %></h1>
<div id="title-divider"></div>
<div class="row">
		
	<div id="wiki-body" class="col-md-9">
		<p>Wiki created by: <%= @wiki.user.email %></p>
		<div class="well well-lg">
			<%= markdown(@wiki.body) %>
		</div>
		<% if current_user && @wiki.collaborators.pluck(:user_id).include?(current_user.id) %>
			<p><strong>You are listed as a collaborator on this wiki</strong></p>
		<% end %>
	</div>
	<div class="col-md-3">
		<% if policy(@wiki).edit? %>
			<%= button_to "Edit This Wiki", edit_wiki_path, method: :get, class: "btn btn-primary" %>
		<% end %>
	</div>
</div>