config/routes.rb
Rails.application.routes.draw do

	root 'welcome#index'
  

	devise_for :users, controllers: { registrations: 'user/registrations' }
	
	devise_scope :user do
		get 'users/edit', :to => 'user/registrations#edit'
    	get 'users/upgrade', :to => 'user/registrations#upgrade'
    	post 'users/downgrade', :to => 'user/registrations#downgrade'
	end
	
	authenticate :user do
		resources :charges
	end
	
	resources :wikis
	resources :collaborators, only: [:create, :destroy]
	resources :charges, only: [:new, :create]
	post '/stripe', :to => 'webhooks#receive'
	
	  
	
	
	
	
	
	
	
	
	
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="https://js.stripe.com/v3/"></script>
</head>
<body>
	
	<nav id="navbar">
		<div id="nav-links" class="pull-left">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Wikis", wikis_path %></li>
		</div>
		<div id="user-nav" class="pull-right">
			<% if user_signed_in? %>
				Signed in as: <strong><%= current_user.email %></strong> | <%= link_to 'Edit Profile', edit_user_registration_path, :class => "navbar-link" %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
			<% else %>
				<%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
			<% end %>
		</div>
	</nav>
	
	<% if notice %>
	<div class="alert alert-success" role="alert"><%= notice %></div>
	<% end %>
	<% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
	<% end %>
	
<%= yield %>

</body>
</html>